spring:
  application:
    name: finalProject

  data:
    mongodb:
      uri: mongodb+srv://ononoki0117:Kuro11350@finalproject.no9i360.mongodb.net/data?retryWrites=true&w=majority&appName=FinalProject

javaprograming:
  app:
    jwtCookieName: ononoki
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
server:
  port: 10700