spring:
  application:
    name: finalProject

  data:
    mongodb:
      uri: mongodb+srv://ononoki0117:Kuro11350@finalproject.no9i360.mongodb.net/data?retryWrites=true&w=majority&appName=FinalProject

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/Documents/local
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update